version: "3"
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - "api_container_db"
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - ./:/usr/src/app
    container_name: api_container_app
    command: npm run dev
  api_container_db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    container_name: api_container_db
    volumes:
      - mydatabase:/var/lib/mysql
volumes:
  mydatabase: {}
