version: "3"
services:
  app:
    build: .
    ports:
      - 8000:8080
    volumes:
      - ./:/usr/src/app
    container_name: api_container_app
    command: npm run dev
  database:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "dpfs_database"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password123"
      MYSQL_ROOT_PASSWORD: "password123"
    container_name: api_container_db
    volumes:
      - mydatabase:/var/lib/mysql
volumes:
  mydatabase: {}
