version: "3"
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/usr/src/app
    container_name: api_container_app
    command: npm run dev
  database:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    container_name: api_container_db
    volumes:
      - mydatabase:/var/lib/mysql
volumes:
  mydatabase: {}
